server:
  port: 8092
  servlet:
    context-path: /api/transfer
management:
  server:
    port: 8191
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: secretpassword
  liquibase:
    default-schema: transfer
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: transfer-app
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
#  file:
#    name: account-transfer.log
#    path: /
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true

